<?php

/**
 * Implementation hook_block().
 *
 * @param string $op
 * @param int $delta
 * @param array $edit
 * @return array
 */

/*****************************************
 *
 *****************************************/
function ruauu_block_info()
{
//  $blocks = array();
  $blocks = array(
    'ruauu' => array(
      'info' => t('Are You REALLY a UU?'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
      'region' => 'content',
      'visibility' => 'BLOCK_VISIBILITY_LISTED',
      'pages' => "<front>",
    )
  );

  return $blocks;
}

/*****************************************
 *
 *****************************************/
function ruauu_block_configure( $delta = '')
{
  if ($delta == 'ruauu') {
    // All we need to provide is the specific configuration options for our
    // block. Drupal will take care of the standard block configuration options
    // (block title, page visibility, etc.) and the save button.
    $db_value = variable_get( 'block_ruauu_body', array('value' => '', 'format' => NULL));
    $form['block_ruauu_body'] = array(
      '#type' => 'text_format',
      '#title' => t('Block contents'),
      '#description' => t('This text will appear in the ruauu block.'),
      '#default_value' => t($db_value['value']),
    );
  }
  return $form;
}

/*****************************************
* Implements hook_block_save().
*
* This hook declares how the configured options for a block
* provided by this module are saved.
*****************************************/
function ruauu_block_save( $delta = '', $edit = array()) {
  // We need to save settings from the configuration form.
  // We need to check $delta to make sure we are saving the right block.
  if ($delta == 'ruauu') {
    // Have Drupal save the string to the database.
    variable_set( 'block_ruauu_body', $edit['block_ruauu_body']);
  }
}

/*****************************************
 *
 *****************************************/
function ruauu_block_view( $delta = '')
{
  $block = array();
  switch ($delta) {
    case 'ruauu':
      drupal_add_js( drupal_get_path('module', 'ruauu') .  '/js/ruauu.js');
      drupal_add_css( drupal_get_path('module', 'ruauu') .  '/css/ruauu.css');
      $block['subject'] = '';
      $block{'content'} = ruauu_block_render( $delta);
      return $block;
      break;
  }
  return $block;
}

/*****************************************
 *  Retrieve upcoming sermons as defined in the VIEW (**NOTE:  this means changes may need to occur via the admin panel for this view)
 *  Then lay it out within the block
 *****************************************/
function ruauu_block_render( $delta = '') {
  switch ($delta) {
    case 'ruauu':
//      $ruauu_block = block_load( 'block', 'ruauu');
      // Block content can be returned in two formats: renderable arrays
      // (as here) are preferred though a simple string will work as well.
      // Block content created through the UI defaults to a string.
      $db_value = variable_get( 'block_ruauu_body', array('value' => '', 'format' => NULL));

//      return $html . $db_value['value'] . '</div>';
      return $db_value['value'];
  }
}