<?php

/**
 * Implementation hook_block().
 *
 * @param string $op
 * @param int $delta
 * @param array $edit
 * @return array
 */

/*****************************************
 *
 *****************************************/
function upcoming_sermons_block_info()
{
//  $blocks = array();
  $blocks = array(
    'upcoming_sermons' => array(
      'info' => t('Upcoming Sermons')),
    'upcoming_sermons_summer' => array(
      'info' => t('Upcoming Sermons for Summer')
    )
  );

  return $blocks;
}

/*****************************************
 *
 *****************************************/
function upcoming_sermons_block_view( $delta = '')
{
  $block = array();
  switch ($delta) {
    case 'upcoming_sermons':
      $block['subject'] = '';
      $block{'content'} = upcoming_sermons_block_render( $delta);
      return $block;
      break;
  }
  return $block;
}

/*****************************************
 *  Retrieve upcoming sermons as defined in the VIEW (**NOTE:  this means changes may need to occur via the admin panel for this view)
 *  Then lay it out within the block
 *****************************************/
function upcoming_sermons_block_render( $delta) {
  $view = views_get_view( 'upcoming_sermons');
  $view->set_display( 'Block');
  $view->pre_execute( array());
  $view->execute();

  $html = '';
  $total_rows = sizeof($view->result);
  foreach ($view->result as $index => $data) {
    switch ($index) {
      /* This Sunday */
      case 0:
          $html = '<h3>This Sunday</h3>' . '<ul class="sermon">' . upcoming_sermons_render_sermon( $data) . '</ul>';
          break;

      /* 2nd Sunday.  Column 1 */
      case 1:
          $html .= '<h3>Upcoming Sundays</h3><div class="one_half">' . upcoming_sermons_render_sermon( $data);
          $html .= '</div>';
          break;

      /*  2nd column of Sundays */
        case 2:
        case 4:
        case 6:
        case 8:
          $html .= '<div class="one_half">' . upcoming_sermons_render_sermon( $data);
          $html .= '</div>';
          break;

      /* 1st column of Sundays */
        case 3:
        case 5:
        case 7:
        case 9:
          $html .= '<div class="one_half" style="clear:both">';
          $html .= upcoming_sermons_render_sermon( $data);
          $html .= '</div>';
          break;
    }
  }
  $html .= '<div style="clear:both;"><h3>Past Sermons</h3>';
  $html .= '  <p>You can visit the <a href="sermons">audio sermons page</a> to listen to past sermons</p>';
  $html .= '</div>';
  return $html;
}

function upcoming_sermons_render_sermon( &$data) {
  $title = $data->_field_data['nid']['entity']->title;
  $html = '<ul class>';
  $html .= '<li class="date"><h4>' . $data->field_field_sunday_date[0]['rendered']['#markup'] . ':&nbsp;&nbsp;' . $data->field_field_speaker[0]['rendered']['#markup'] . '</h4></li>';
  $html .= '<li class="topic"><span style="font-style:italic;font-weight:bold;">' . $title . '</span>: ' . $data->field_field_sermon_short_description[0]['rendered']['#markup'] . '</li>';
  $html .= '</ul>';
  return $html;
}