<?php

/**
 * Implementation hook_block().
 *
 * @param string $op
 * @param int $delta
 * @param array $edit
 * @return array
 */

/*****************************************
 *
 *****************************************/
function upcoming_sermons_block_info()
{
//  $blocks = array();
  $blocks = array(
    'upcoming_sermons' => array(
      'info' => t('Upcoming Sermons'),
    )
  );

  return $blocks;
}

/*****************************************
 *
 *****************************************/
function upcoming_sermons_block_view( $delta = '')
{
  $block = array();
  switch ($delta) {
    case 'upcoming_sermons':
      $block['subject'] = '';
      $block{'content'} = upcoming_sermons_block_render( $delta);
      return $block;
      break;
  }
  return $block;
}

/*****************************************
 *  Retrieve upcoming sermons as defined in the VIEW (**NOTE:  this means changes may need to occur via the admin panel for this view)
 *  Then lay it out within the block
 *****************************************/
function upcoming_sermons_block_render() {
  $view = views_get_view( 'upcoming_sermons');
  $view->set_display( 'Block');
  $view->pre_execute( array());
  $view->execute();

  $html = '';
  $total_rows = sizeof($view->result);
  foreach ($view->result as $index => $data) {
    switch ($index) {
      /* This Sunday */
      case 0:
          $html = '<h3>This Sunday</h3>' . '<ul class="sermon">' . upcoming_sermons_render_sermon( $data) . '</ul>';
          break;

      /* 2nd Sunday */
      case 1:
          $html .= '<h3>Upcoming Sundays</h3><div class="one_half"><ul class="sermon">' . upcoming_sermons_render_sermon( $data);
          $html .= ($total_rows == $index+1) ? '</ul></div>' : '';   /* close tags if this is the last row */
          break;

      /* 3rd or 5th Sunday */
        case 2:
        case 4:
          $html .= '</br>';
          $html .= upcoming_sermons_render_sermon( $data);
          $html .= '</ul></div>';
          break;

      /*  4th Sunday */
        case 3:
          $html .= '<div class="one_half"><ul class="sermon">' . upcoming_sermons_render_sermon( $data);
          $html .= ($total_rows == $index+1) ? '</ul></div>' : '';   /* close tags if this is the last row */
          break;
    }
  }
  return $html;
}

function upcoming_sermons_render_sermon( &$data) {
//  $pic_info['item'] = $data->field_field_picture[0]['rendered']['#item'];
//  $pic_info['image_style'] = $data->field_field_picture[0]['rendered']['#image_style'];
//  $pic_info['path'] = $data->field_field_picture[0]['rendered']['#path'];
  $title = $data->_field_data['nid']['entity']->title;
  $html = '<ul class>';
  $html .= '<li class="date"><h4>' . $data->field_field_sunday_date[0]['rendered']['#markup'] . ':&nbsp;&nbsp;' . $data->field_field_speaker[0]['rendered']['#markup'] . '</h4></li>';
//  $html .= '<li class="speaker"><h4>' . $data->field_field_speaker[0]['rendered']['#markup'] . '</h4></li>';
//  $html .= '<li class="pic">' . theme_image_formatter( $pic_info) . '</li>';
  $html .= '<li class="topic"><span style="font-style:italic;font-weight:bold;">' . $title . '</span>: ' . $data->field_field_sermon_short_description[0]['rendered']['#markup'] . '</li>';
//  $html .= '<li class="desc">' . $data->field_body[0]['rendered']['#markup'] . '</li>';
//  $html .= '<li class="pic">' . theme_image_formatter( $data->field_field_picture[0]['rendered']) . '</li>';
  $html .= '</ul>';
  return $html;
}